### ISSUE TITLE
Cannot Convert World

### ISSUE THREAD

**Issue by rsherry3767** [HiveGamesOSS/Chunker#109]
### Chunker Version

1.3.0-main-2cdf4aa

### Input World Version

Java 1.12.2

### Output World Version

Bedrock

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: Failed to open selected file.

**Comment by FormallyMyles** [comment]
Do you know if there's anything special about the specific world you're uploading? e.g. you used other software to edit it

Otherwise, If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.
