### ISSUE TITLE
Chunker not allocating all available memory when used through the GUI 

### ISSUE THREAD

**Issue by Electronik21** [HiveGamesOSS/Chunker#125]
### Chunker Version

1.3.1-main-b157b5c

### Input World Version

Java 1.18.2

### Output World Version

Bedrock 1.18.30

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: Your system ran out of memory while converting, please try again, use a smaller world or try a different machine.

I have a ~1.8GB world I'm trying to convert, but it always says I'm "out of memory" before it even starts. My system has 16GB of memory and whenever it fails it's only using about 4GB, and my pc has plenty left over.

**Comment by Electronik21** [comment]
[main.log](https://github.com/user-attachments/files/17692318/main.log)
Btw trying the CLI gave the same error as in the log, but I got it to work by using the `-Xmx8G` flag. Maybe add an option for custom flags in the gui?

**Comment by FormallyMyles** [comment]
Definitely odd that it didn't decide to allocate enough RAM but we'll definitely take a look further into this, thanks!

**Comment by AbdullahAlass** [comment]
Hello brother, I encountered the same problem. I tried to convert a 12GB computer-generated world to a Bedrock file, and I got the same issue.

**Comment by lumberaellaijahkeint-dev** [comment]
Hello!! Running to a similar problem, my I wanted to convert a java world to bedrock, but it keeps saying I run out of system memory, I have 16gb of ram though and I'm running on windows x86 (chunker version)

**Comment by FormallyMyles** [comment]
The error you're seeing is because Chunker doesn't have enough memory to convert your world, this is usually because the world is quite big, or you don't have enough available memory (RAM). Chunker by default uses 75% of your available memory, so you might find that closing other applications before converting your world allows it to use the memory it needs.

You can also tell Chunker how much memory you want it to use, you need to run it from command-line in the form of `Chunker.exe -Xmx8G` to tell Chunker to use a maximum of 8 gigabytes of memory.

Alternatively, if your world is on Java edition you might find that using tools like MCASelector allow you to remove parts of your world that you haven't inhabited removing the requirement of needing more memory. You can also prune the world in the Advanced Settings of Chunker which may also help if you the problem doesn't occur prior to that.

We can look further, but in most cases a large world does require more memory (especially with compression of the files), if you'd like us to we would need (open a new issue):
- The world size
- How much memory your computer has
- A copy of the world
