### ISSUE TITLE
Wolrd zip wont load 

### ISSUE THREAD

**Issue by Teyo27** [HiveGamesOSS/Chunker#126]
### Chunker Version

1.3.1-main-b157b5c

### Input World Version

Java

### Output World Version

Bedrock

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: Failed to open selected file.

**Comment by FormallyMyles** [comment]
Is there any further information you can provide about the world you're trying to convert?

Otherwise, 
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.
