### ISSUE TITLE
Error Displayed: Unable to run chunker-cli backend.

### ISSUE THREAD

**Issue by Joeschmo2187** [HiveGamesOSS/Chunker#150]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

Java

### Output World Version

Java

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `Unable to run chunker-cli backend.`

**Comment by FormallyMyles** [comment]
Have you tried closing the application and running it again? This can happen if you run the application twice before it's fully loaded. Otherwise, If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
