### ISSUE TITLE
Unable to connect to backend

### ISSUE THREAD

**Issue by wvzack** [HiveGamesOSS/Chunker#154]
### Chunker Version

1.1.3-main-ac2a40f

### Input World Version

java 1.20

### Output World Version

bedrock 1.21

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: Unable to run chunker-cli backend.

**Comment by FormallyMyles** [comment]
Would you mind trying to close Chunker, then opening it once, ensure you don't open it multiple times as sometimes this issue is caused by that and Chunker doesn't extract properly.

You can also try the .zip version for Windows (note: It currently isn't signed so it may cause SmartScreen on Windows to appear) - https://github.com/HiveGamesOSS/Chunker/releases/download/1.4.0/Chunker-1.4.0-windows-x86.zip

Otherwise, If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
