### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by David540928** [HiveGamesOSS/Chunker#161]
### Chunker Version

1.4.1-main-6cce3ef

### Input World Version

Java .1.17.1

### Output World Version

Java .1.21.3

### Platform / Operating System

win32-x64-10.0.26120

### Issue Description

Error Displayed: `Your system ran out of memory while converting, please try again, use a smaller world or try a different machine.`

**Comment by FormallyMyles** [comment]
The error you're seeing is because Chunker doesn't have enough memory to convert your world, this is usually because the world is quite big, or you don't have enough available memory (RAM). Chunker by default uses 75% of your available memory, so you might find that closing other applications before converting your world allows it to use the memory it needs.

You can also tell Chunker how much memory you want it to use, you need to run it from command-line in the form of `Chunker.exe -Xmx8G` to tell Chunker to use a maximum of 8 gigabytes of memory.

Alternatively, if your world is on Java edition you might find that using tools like MCASelector allow you to remove parts of your world that you haven't inhabited removing the requirement of needing more memory.

We can look further, but in most cases a large world does require more memory (especially with compression of the files), if you'd like us to, we would need:
- The world size
- How much memory your computer has
- A copy of the world

In your specific case, you may want to just use Minecraft Java to upgrade the world as it will do it as you load the chunks.
