### ISSUE TITLE
Unable to run chunker -cli backend

### ISSUE THREAD

**Issue by pbBadger** [HiveGamesOSS/Chunker#164]
### Chunker Version

1.4.1-main-6cce3ef

### Input World Version

Bedrock

### Output World Version

Java

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Displayed: `Unable to run chunker-cli backend.`

**Comment by FormallyMyles** [comment]
Would you mind trying to close Chunker, then opening it once, ensure you don't open it multiple times as sometimes this issue is caused by that and Chunker doesn't extract properly.

You can also try the .zip version for Windows - https://github.com/HiveGamesOSS/Chunker/releases/download/1.4.1/Chunker-1.4.1-windows-x86.zip

Otherwise, If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
