### ISSUE TITLE
Oops, Failed to convert world. Errore 0192e14d-49d4-4b6a-ae0b-ce190f14ce2a

### ISSUE THREAD

**Issue by GimboAssurdo** [HiveGamesOSS/Chunker#172]
### Chunker Version

1.4.1-main-6cce3ef

### Input World Version

Bedrock. La versione non me la ricordo

### Output World Version

Java 1.20.4

### Platform / Operating System

Windows 10

### Issue Description

Quasi alla fine del caricamento di conversione compare questo messaggio: Oops, Failed to convert world. Error 0192e14d-49d4-4b6a-ae0b-ce190f14ce2a

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by GimboAssurdo** [comment]
[main.log](https://github.com/user-attachments/files/18048273/main.log)

**Comment by FormallyMyles** [comment]
The error you're seeing is because Chunker doesn't have enough memory to convert your world, this is usually because the world is quite big, or you don't have enough available memory (RAM). Chunker by default uses 75% of your available memory, so you might find that closing other applications before converting your world allows it to use the memory it needs.

You can also tell Chunker how much memory you want it to use, you need to run it from command-line in the form of `Chunker.exe -Xmx8G` to tell Chunker to use a maximum of 8 gigabytes of memory.

We can look further, but in most cases a large world does require more memory (especially with compression of the files), if you'd like us to we would need:
- The world size
- How much memory your computer has
- A copy of the world
