### ISSUE TITLE
Error while trying to convert a marketplace world

### ISSUE THREAD

**Issue by 1Emilis1** [HiveGamesOSS/Chunker#73]
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.21.30

### Output World Version

Java 1.21.1

### Platform / Operating System

win32-x64-10.0.19044

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

**Comment by FormallyMyles** [comment]
If you're opening a world which is based on a Marketplace map, please note it's not possible to convert these as they're encrypted.

Otherwise, If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
It sounds like you're likely having the same issue as https://github.com/HiveGamesOSS/Chunker/issues/71, do note though that Marketplace worlds do tend to be encrypted so your mileage may vary (it may depend on the world).
