### ISSUE TITLE
Oops, Failed to connect to backend

### ISSUE THREAD

**Issue by Netroruz** [HiveGamesOSS/Chunker#98]
### Chunker Version

1.3.0-main-2cdf4aa

### Input World Version

Bedrock 1.21.41

### Output World Version

Java 1.21

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: Unable to run chunker-cli backend.

**Comment by FormallyMyles** [comment]
Have you tried closing and reopening Chunker, otherwise:

If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
Going to close this issue as I haven't heard back from you, if you're still running into this please provide the above and we can look further :)
